apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: jwt
  labels:
    global: "false"
disabled: false
config:
  claims_to_verify:
  - exp
  - nbf
  key_claim_name: iss
plugin: jwt
---
# acl plugin with whitelist 
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: coffee-acl
  labels:
    global: "false"
disabled: false
config:
  hide_groups_header: true
  whitelist: ["coffee", "tea"]
plugin: acl
    {{- range $consumer := .consumers }}
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: {{ $consumer }}
username: {{ $consumer }}
custom_id: {{ $consumer }}
---
apiVersion: configuration.konghq.com/v1
kind: KongCredential
group: {{ $consumer }}
metadata:
  name: {{ $consumer }}-cred
consumerRef: {{ $consumer }}
type: jwt
config:
  key: urn:mydomain.com/{{ $consumer }}
  rsa_public_key: |
    -----BEGIN PUBLIC KEY-----
    MYPUBLICKEY
-----END PUBLIC KEY-----
  algorithm: RS512
  group: "{{ $consumer }}"
